const functions = require("firebase-functions");
const { defineString } = require('firebase-functions/params');
const { CohereClientV2 } = require("cohere-ai");
const fs = require("fs");
const path = require("path");

const cohereApiKey = defineString('COHERE_API_KEY');
const cohereApiKeyCred = process.env.COHERE_API_KEY || cohereApiKey.value();

const MODEL = "command-a-translate-08-2025";

const client = new CohereClientV2({
  token: cohereApiKeyCred,
  clientName: "cioos-metadata-entry-form",
});

// Load prompt template (synced from cioos-commons by generate-translation-config.js)
// Glossary is already baked into the template by cioos-commons CI.
const promptTemplate = fs.readFileSync(
  path.join(__dirname, "translation-prompt-template.txt"),
  "utf8"
);

// Load version metadata (generated by generate-translation-config.js)
let translationMeta = { commonsVersion: "unknown" };
try {
  translationMeta = require("./translation-meta.json");
} catch {
  // translation-meta.json may not exist in dev; that's ok
}

function buildPrompt(originalText, sourceLanguageCode, targetLanguageCode) {
  const sourceLang = sourceLanguageCode === 'en' ? 'Canadian English' : 'Canadian French';
  const targetLang = targetLanguageCode === 'en' ? 'Canadian English' : 'Canadian French';

  return promptTemplate
    .replace("{{sourceLang}}", sourceLang)
    .replace("{{targetLang}}", targetLang)
    .replace("{{originalText}}", originalText);
}

function buildTranslationMessage() {
  return `Cohere ${MODEL}, cioos-commons@${translationMeta.commonsVersion}`;
}

// Translate up to 5000 characters at a time using Cohere
const translateText = async (
  originalText,
  sourceLanguageCode,
  targetLanguageCode
) => {
  const prompt = buildPrompt(originalText, sourceLanguageCode, targetLanguageCode);

  try {
    const response = await client.chat({
      model: MODEL,
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    // Extract the translation from the response
    if (
      response.message &&
      response.message.content &&
      response.message.content.length > 0
    ) {
      let translatedText = response.message.content[0].text;
      // Strip <text_to_translate> wrapper tags if the model echoes them back
      const match = translatedText.match(/<text_to_translate>\s*([\s\S]*?)\s*<\/text_to_translate>/);
      if (match) translatedText = match[1];
      return { TranslatedText: translatedText };
    } else {
      throw new Error("No translation received from Cohere API");
    }
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("translateText error: ", err);
    throw err;
  }
};

exports.translate = functions.https.onCall(async (data, context) => {
  if (!context.auth || !context.auth.token)
    throw new functions.https.HttpsError("unauthenticated");

  const { text, fromLang } = data;

  const toLang = fromLang === "en" ? "fr" : "en";

  const res = await translateText(text, fromLang, toLang);
  return {
    translatedText: res.TranslatedText,
    translationMessage: buildTranslationMessage(),
  };
});
