import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { SCHEMA_VERSION } from "../version";

/**
 * The browsable docs under schema/docs/build/ are generated by Python
 * (`npm run schema:docs`) and committed, because the GitHub Pages deploy is
 * Node-only and cannot generate them at deploy time.
 *
 * This suite cannot regenerate them to check freshness, so it compares the
 * version stamp the generator writes. Bumping the schema without regenerating
 * the docs fails here.
 */

const BUILD = join(process.cwd(), "schema", "docs", "build");

const EXPECTED_FILES = [
  "index.html",
  "SCHEMA_VERSION",
  "en/index.html",
  "en/fields.html",
  "en/fields.md",
  "en/conditional-requirements.html",
  "fr/index.html",
  "fr/fields.html",
  "fr/fields.md",
  "fr/conditional-requirements.html",
];

describe("generated documentation", () => {
  it("has been generated", () => {
    expect(
      existsSync(BUILD),
      "schema/docs/build is missing — run `npm run schema:docs`"
    ).toBe(true);
  });

  it.each(EXPECTED_FILES)("includes %s", (relative) => {
    expect(existsSync(join(BUILD, relative))).toBe(true);
  });

  it("is not stale", () => {
    const stamped = readFileSync(join(BUILD, "SCHEMA_VERSION"), "utf8").trim();
    expect(
      stamped,
      `docs were built for schema ${stamped} but the schema is now ${SCHEMA_VERSION} — run \`npm run schema:docs\``
    ).toBe(SCHEMA_VERSION);
  });

  it("shows the current version on the landing page", () => {
    const html = readFileSync(join(BUILD, "index.html"), "utf8");
    expect(html).toContain(SCHEMA_VERSION);
  });

  /**
   * json-schema-for-humans' js_offline template emits a <script> for a
   * FontAwesome kit it never vendors, which 404s on the published page. The
   * build strips it; this makes sure a jsfh upgrade doesn't quietly bring it
   * back.
   */
  it("references no asset it does not ship", () => {
    const assets = join(BUILD, "assets");
    const shipped = new Set();
    ["css", "js"].forEach((dir) => {
      const full = join(assets, dir);
      if (existsSync(full)) {
        readdirSync(full).forEach((name) => shipped.add(`${dir}/${name}`));
      }
    });

    ["en", "fr"].forEach((language) => {
      const html = readFileSync(join(BUILD, language, "fields.html"), "utf8");
      const referenced = [...html.matchAll(/(?:href|src)="\.\.\/assets\/([^"]+)"/g)]
        .map((match) => match[1])
        .filter((name) => name.endsWith(".css") || name.endsWith(".js"));

      expect(referenced.length).toBeGreaterThan(0);
      const missing = referenced.filter((name) => !shipped.has(name));
      expect(missing, `${language}/fields.html references missing assets`).toEqual(
        []
      );
    });
  });

  it("loads no subresource from an external host", () => {
    // The pages must render offline and under a strict CSP. Only tags the
    // browser actually fetches count — an <a href> to the generator's homepage
    // in the footer is attribution, not a load.
    const subresource = /<(?:link|script|img|iframe|source)\b[^>]*\b(?:href|src)="((?:https?:)?\/\/[^"]*)"/gi;

    ["en", "fr"].forEach((language) => {
      const html = readFileSync(join(BUILD, language, "fields.html"), "utf8");
      const external = [...html.matchAll(subresource)].map((match) => match[1]);
      expect(external, `${language}/fields.html loads an external resource`).toEqual(
        []
      );
    });
  });

  it("renders French content in the French field reference", () => {
    const french = readFileSync(join(BUILD, "fr", "fields.md"), "utf8");
    expect(french).toContain("Catégorie thématique");
    expect(french).toContain("Étendue géographique");
  });
});
