import React from "react";
import {
  Grid,
  Typography,
  TextField,
  Button,
  Checkbox,
  FormControlLabel,
  FormControl,
  FormLabel,
  RadioGroup,
  Radio,
  Alert,
  Tooltip,
  IconButton,
  InputAdornment,
  CircularProgress,
} from "@mui/material";
import {
  Save,
  Delete,
  PlayArrow,
  Visibility,
  VisibilityOff,
} from "@mui/icons-material";
import FormSection from "../FormShell/FormSection";
import { I18n, En, Fr } from "../I18n";

const SUFFIX_MODES = [
  {
    key: "default",
    en: "Default (auto-generated by DataCite)",
    fr: "Par défaut (généré automatiquement par DataCite)",
  },
  {
    key: "identifier",
    en: "Form identifier (record identifier)",
    fr: "Identifiant du formulaire (identifiant de l'enregistrement)",
  },
  {
    key: "manual",
    en: "Manual (user-defined value)",
    fr: "Manuel (valeur définie par l'utilisateur)",
  },
];

// DOI/DataCite half of the admin page. Presentational: `values` is Admin's
// state and every mutation goes back through a named handler, so this file
// holds no state of its own.
export default function DataciteSettings({
  values,
  onChange,
  onToggleDoiCreation,
  onToggleSuffixMode,
  onTestCredentials,
  onSave,
  onClearFields,
  onToggleShowPassword,
  onMouseDownPassword,
  onDismissTestResult,
}) {
  const {
    isDoiCreationEnabled,
    credentialsStored,
    showPassword,
    datacitePrefix,
    datacitePrefixValid,
    dataciteAccountId,
    dataciteApiDomain,
    datacitePass,
    doiStatusManagement,
    doiSuffixModes,
    testingCredentials,
    testResult,
  } = values;

  return (
    <FormSection
      title={<I18n en="DOI Creation Settings" fr="Paramètres de création de DOI" />}
    >
      <Grid container spacing={2}>
        <Grid
          size={12}
          container
          alignItems="center"
          justifyContent="space-between"
        >
          <Grid>
            <FormControlLabel
              control={
                <Checkbox
                  checked={isDoiCreationEnabled || false}
                  onChange={onToggleDoiCreation}
                />
              }
              label={
                <I18n
                  en="Enable DOI Creation"
                  fr="Activer la création de DOI"
                />
              }
            />
          </Grid>
          {isDoiCreationEnabled && (
            <Grid size={12}>
              <Alert severity={credentialsStored ? "success" : "warning"}>
                <I18n>
                  <En>
                    {credentialsStored
                      ? "DataCite credentials are saved. Enter new values below to update them."
                      : "No DataCite credentials stored. Please enter your credentials below."}
                  </En>
                  <Fr>
                    {credentialsStored
                      ? "Les identifiants DataCite sont enregistrés. Entrez de nouvelles valeurs ci-dessous pour les mettre à jour."
                      : "Aucun identifiant DataCite enregistré. Veuillez entrer vos identifiants ci-dessous."}
                  </Fr>
                </I18n>
              </Alert>
            </Grid>
          )}
        </Grid>

        {isDoiCreationEnabled && (
          <>
            <Grid size={12}>
              <FormControl>
                <FormLabel>
                  <I18n en="DataCite API" fr="API DataCite" />
                </FormLabel>
                <RadioGroup
                  row
                  name="dataciteApiDomain"
                  value={dataciteApiDomain}
                  onChange={onChange}
                >
                  <FormControlLabel
                    value="production"
                    control={<Radio />}
                    label="Production (api.datacite.org)"
                  />
                  <FormControlLabel
                    value="test"
                    control={<Radio />}
                    label="Test (api.test.datacite.org)"
                  />
                </RadioGroup>
              </FormControl>
            </Grid>

            <Grid size={12}>
              <FormControl>
                <FormLabel>
                  <I18n
                    en="DOI Status Management"
                    fr="Gestion du statut DOI"
                  />
                </FormLabel>
                <Typography
                  variant="caption"
                  sx={{ display: "block", mb: 0.5, color: "text.secondary" }}
                >
                  <I18n>
                    <En>
                      When set to &quot;Managed from this form&quot;, reviewers
                      will be prompted to set the DOI status (findable or
                      registered) when publishing or unpublishing records. The
                      DOI status can also be changed directly from the record
                      form.
                    </En>
                    <Fr>
                      Lorsque défini sur « Géré depuis ce formulaire », les
                      réviseurs seront invités à définir le statut du DOI
                      (trouvable ou enregistré) lors de la publication ou du
                      retrait d&apos;un enregistrement. Le statut peut également
                      être modifié directement depuis le formulaire.
                    </Fr>
                  </I18n>
                </Typography>
                <RadioGroup
                  row
                  name="doiStatusManagement"
                  value={doiStatusManagement}
                  onChange={onChange}
                >
                  <FormControlLabel
                    value="datacite"
                    control={<Radio />}
                    label={
                      <I18n
                        en="Managed via DataCite portal"
                        fr="Géré via le portail DataCite"
                      />
                    }
                  />
                  <FormControlLabel
                    value="form"
                    control={<Radio />}
                    label={
                      <I18n
                        en="Managed from this form"
                        fr="Géré depuis ce formulaire"
                      />
                    }
                  />
                </RadioGroup>
              </FormControl>
            </Grid>

            <Grid size={12}>
              <FormControl component="fieldset">
                <FormLabel component="legend">
                  <I18n
                    en="DOI Suffix Generation"
                    fr="Génération du suffixe DOI"
                  />
                </FormLabel>
                <Typography
                  variant="caption"
                  sx={{ display: "block", mb: 0.5, color: "text.secondary" }}
                >
                  <I18n
                    en="Select one or more methods users may pick from when generating a DOI suffix."
                    fr="Sélectionnez une ou plusieurs méthodes que les utilisateurs pourront choisir pour générer un suffixe DOI."
                  />
                </Typography>
                {SUFFIX_MODES.map(({ key, en, fr }) => (
                  <FormControlLabel
                    key={key}
                    control={
                      <Checkbox
                        checked={(doiSuffixModes || []).includes(key)}
                        onChange={() => onToggleSuffixMode(key)}
                      />
                    }
                    label={<I18n en={en} fr={fr} />}
                  />
                ))}
              </FormControl>
            </Grid>

            <Grid size={12}>
              <TextField
                name="datacitePrefix"
                label={<I18n en="DataCite Prefix" fr="Préfixe DataCite" />}
                placeholder="10.0000"
                value={datacitePrefix || ""}
                onChange={onChange}
                fullWidth
                error={!datacitePrefixValid}
                helperText={
                  !datacitePrefixValid &&
                  "Prefix must start with '10.' followed by numbers."
                }
              />
            </Grid>

            <Grid size={12}>
              <TextField
                name="dataciteAccountId"
                label={<I18n en="Account ID" fr="Identifiant du compte" />}
                value={dataciteAccountId || ""}
                onChange={onChange}
                fullWidth
              />
            </Grid>

            <Grid size={12}>
              <TextField
                name="datacitePass"
                label={<I18n en="Password" fr="Mot de passe" />}
                placeholder={credentialsStored ? "••••••••" : ""}
                InputLabelProps={{
                  shrink: credentialsStored || !!datacitePass,
                }}
                helperText={
                  credentialsStored && !datacitePass ? (
                    <I18n
                      en="A password is saved. Enter Account ID + Password to replace it."
                      fr="Un mot de passe est enregistré. Entrez l'identifiant et le mot de passe pour le remplacer."
                    />
                  ) : undefined
                }
                type={showPassword ? "text" : "password"}
                onChange={onChange}
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <IconButton
                        onClick={onToggleShowPassword}
                        onMouseDown={onMouseDownPassword}
                        edge="end"
                        aria-label={
                          showPassword ? "Hide password" : "Show password"
                        }
                      >
                        {showPassword ? <VisibilityOff /> : <Visibility />}
                      </IconButton>
                    </InputAdornment>
                  ),
                }}
                fullWidth
              />
            </Grid>

            {testResult && (
              <Grid size={12}>
                <Alert
                  severity={testResult.success ? "success" : "error"}
                  onClose={onDismissTestResult}
                >
                  {testResult.message}
                  {!testResult.success &&
                    testResult.message?.includes(
                      "No DataCite credentials"
                    ) && (
                      <Typography variant="body2" sx={{ mt: 0.5 }}>
                        <I18n
                          en='To fix this: enter your Account ID and Password above and click "Update DataCite Settings", then test again.'
                          fr="Pour corriger cela : entrez votre identifiant de compte et votre mot de passe ci-dessus, cliquez sur « Mettre à jour les paramètres DataCite », puis testez à nouveau."
                        />
                      </Typography>
                    )}
                </Alert>
              </Grid>
            )}

            <Grid size={12} container spacing={1} justifyContent="flex-end">
              <Grid>
                <Tooltip
                  title={
                    datacitePass ? (
                      <I18n
                        en="Save credentials first before testing"
                        fr="Enregistrez les identifiants avant de tester"
                      />
                    ) : (
                      ""
                    )
                  }
                >
                  <span>
                    <Button
                      startIcon={
                        testingCredentials ? (
                          <CircularProgress size={20} />
                        ) : (
                          <PlayArrow />
                        )
                      }
                      variant="outlined"
                      color="secondary"
                      onClick={onTestCredentials}
                      disabled={
                        !credentialsStored ||
                        testingCredentials ||
                        !!datacitePass
                      }
                    >
                      <I18n
                        en="Test Credentials"
                        fr="Tester les identifiants"
                      />
                    </Button>
                  </span>
                </Tooltip>
              </Grid>
              <Grid>
                <Button
                  startIcon={<Delete />}
                  variant="outlined"
                  color="error"
                  onClick={onClearFields}
                  disabled={!credentialsStored}
                >
                  <I18n
                    en="Clear DataCite Credentials"
                    fr="Effacer les identifiants DataCite"
                  />
                </Button>
              </Grid>
              <Grid>
                <Button
                  startIcon={<Save />}
                  variant="contained"
                  color="primary"
                  onClick={onSave}
                >
                  <I18n>
                    <En>
                      {credentialsStored ? "Update" : "Save"} DataCite Settings
                    </En>
                    <Fr>
                      {credentialsStored ? "Mettre à jour" : "Enregistrer"} les
                      paramètres DataCite
                    </Fr>
                  </I18n>
                </Button>
              </Grid>
            </Grid>
          </>
        )}
      </Grid>
    </FormSection>
  );
}
