
const mockMetadataRecord = {
    "title": {
        "en": "This is a mock record",
        "fr": "Il s'agit d'un faux record",
    },
    "abstract": {
        "en": "This is a mock record to be used in unit tests, to ensure the continued functionality of the mapping function.",
        "fr": "Il s'agit d'un enregistrement fictif à utiliser dans les tests unitaires, afin de garantir la fonctionnalité continue de la fonction de mappage.",
    },
    "keywords": {
        "en": [
            "abundance and biomass",
        ],
        "fr": [
            "abondance et biomasse",
        ],
    },
    "eov": [
        "dissolvedOrganicCarbon",
    ],
    "progress": "onGoing",
    "distribution": [],
    "dateStart": "2023-10-01T19:00:00.000Z",
    "dateEnd": "2023-10-04T19:00:00.000Z",
    "map": {
        "east": "-160",
        "north": "60",
        "polygon": "",
        "south": "45",
        "west": "-120",
    },
    "verticalExtentMin": "",
    "verticalExtentMax": "",
    "datePublished": "2023-10-26T19:00:00.000Z",
    "dateRevised": null,
    "edition": "1.1",
    "recordID": "-Nhi6_2lQjNwKkzdv_Qu",
    "instruments": [],
    "platform": "",
    "platformID": "",
    "platformDescription": "",
    "language": "en",
    "license": "CC-BY-4.0",
    "contacts": [
        {
            "role": [
                "custodian",
            ],
            "orgName": "Royal Roads University",
            "orgEmail": "",
            "orgURL": "http://www.royalroads.ca/",
            "orgAdress": "",
            "orgCity": "Victoria",
            "orgCountry": "Canada",
            "orgRor": "https://ror.org/05w4ste42",
            "indPosition": "",
            "indEmail": "",
            "indOrcid": "",
            "givenNames": "Austen",
            "lastName": "Sorochak",
            "inCitation": true,
        },
        {
            "role": [],
            "orgName": "",
            "orgEmail": "",
            "orgURL": "",
            "orgAdress": "",
            "orgCity": "",
            "orgCountry": "",
            "orgRor": "",
            "indPosition": "",
            "indEmail": "",
            "indOrcid": "",
            "givenNames": "Jack",
            "lastName": "PumpkinKing",
            "inCitation": true,
        },
        {
            "role": [
                "publisher",
                "funder",
            ],
            "orgName": "Royal Roads University",
            "orgEmail": "",
            "orgURL": "",
            "orgAdress": "",
            "orgCity": "",
            "orgCountry": "",
            "orgRor": "",
            "indPosition": "",
            "indEmail": "",
            "indOrcid": "",
            "givenNames": "",
            "lastName": "",
            "inCitation": true,
        },
    ],
    "status": "",
    "comment": "",
    "limitations": "",
    "lastEditedBy": {
        "displayName": "Austen Sorochak",
        "email": "austen.sorochak@hakai.org",
    },
    "category": "",
    "verticalExtentDirection": "",
    "datasetIdentifier": "",
    "doiCreationStatus": "",
    "noPlatform": false,
    "filename": "",
    "organization": "",
    "timeFirstPublished": "",
    "identifier": "b6f44266-5815-48bb-bd0c-dd050c6fe465",
    "created": "2023-11-03T21:04:37.548Z",
    "userID": "gP03Su7SUndv1bwlW6YnBhtAwSw2",
}

export default mockMetadataRecord