[project]
name = "cioos-records-update"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "firebase-to-xml",
    "flask>=1.1.4",
    "gunicorn>=23.0.0",
    "metadata-xml",
    "python-dotenv>=1.0.1",
    "sentry-sdk>=2.19.2",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]

[tool.uv.sources]
metadata-xml = { git = "https://github.com/cioos-siooc/metadata-xml.git" }
firebase-to-xml = { git = "https://github.com/cioos-siooc/metadata-entry-form.git", subdirectory = "firebase_to_xml", rev = "migrate-cioos-form" }
