import React from "react";
import { Paper, TextField } from "@material-ui/core";
import { En, Fr } from "../I18n";

import BilingualTextInput from "./BilingualTextInput";
import SelectInput from "./SelectInput";
import RequiredMark from "./RequiredMark";

import { QuestionText, SupplementalText, paperClass } from "./QuestionStyles";
import { validateField } from "../validate";

const MetadataTab = ({ disabled, record, handleInputChange }) => (
  <div>
    <Paper style={paperClass}>
      <QuestionText>
        <En>
          Metadata Identifier. This ID is autogenerated by the form. It is used
          to track records in the CKAN catalogue.
        </En>
        <Fr>
          Identificateur de métadonnées Cet ID est généré automatiquement par le
          formulaire. Il est utilisé pour suivre les dossiers dans le catalogue
          CKAN.
        </Fr>
      </QuestionText>
      <TextField
        name="identifier"
        value={record.identifier}
        onChange={(e) => handleInputChange(e)}
        disabled
        fullWidth
      />
    </Paper>

    <Paper style={paperClass}>
      <QuestionText>
        <En>What is primary language of the dataset?</En>
        <Fr>Quelle est la langue principale du jeu de données?</Fr>
        <RequiredMark passes={validateField(record, "language")} />
      </QuestionText>
      <SelectInput
        name="language"
        value={record.language}
        onChange={(e) => handleInputChange(e)}
        options={["en", "fr"]}
        optionLabels={["English", "Français"]}
        disabled={disabled}
      />
    </Paper>
    <Paper style={paperClass}>
      <QuestionText>
        <En>How is the resource licensed?</En>
        <Fr>Comment la ressource est-elle sous licence?</Fr>
        <RequiredMark passes={validateField(record, "license")} />
        <SupplementalText>
          <En>
            We recommend that the Creative Commons Attribution 4.0 International
            licence (CC-BY 4.0) be applied as the default licence for all
            datasets that will be made available through the CIOOS platform.
            This allows for open sharing and adaptation of the data provided
            that the original creator is attributed. Releasing the data as
            public domain (Creative Commons 0), which imposes no restrictions of
            any kind is also acceptable. For datasets made available by
            Government of Canada departments and agencies, the Open Government
            Licence - Canada can be used, which is very similar to CC-BY as it
            allows for open sharing and adaptation of the data provided that the
            original creator of the data is properly attributed.
          </En>
          <Fr>
            Nous recommandons que la licence Creative Commons Attribution 4.0
            International (CC-BY 4.0) soit appliquée comme licence par défaut
            pour tous les ensembles de données qui seront disponibles via la
            plateforme CIOOS. Cela permet le partage ouvert et l'adaptation des
            données à condition que le créateur original soit attribué. La
            diffusion des données en tant que domaine public (Creative Commons
            0), qui n'impose aucune restriction d'aucune sorte est également
            acceptable. Pour les ensembles de données mis à la disposition des
            ministères et organismes du gouvernement du Canada, on peut utiliser
            la Licence pour gouvernement ouvert - Canada, qui est très semblable
            à CC-BY, car elle permet le partage ouvert et l'adaptation des
            données à condition que le créateur original des données soit
            correctement attribué.
          </Fr>
        </SupplementalText>
      </QuestionText>
      <SelectInput
        name="license"
        value={record.license}
        onChange={(e) => handleInputChange(e)}
        optionLabels={[
          "Creative Commons Attribution 4.0",
          "Creative Commons 0",
          "Open Government Licence - Canada",
          "Apache License, Version 2.0",
        ]}
        options={[
          "CC-BY-4.0",
          "CC0",
          "government-open-license-canada",
          "Apache-2.0",
        ]}
        disabled={disabled}
      />
    </Paper>
    <Paper style={paperClass}>
      <QuestionText>
        <En>
          What are the limitations affecting the fitness for use of the resource
          or metadata?
        </En>
        <Fr>
          Quelles sont les limites qui influent sur l'aptitude à l'utilisation
          de la ressource ou des métadonnées?
        </Fr>
        <SupplementalText>
          <En>
            Eg: <i>Appropriate credit must be given to...</i>
          </En>
          <Fr>
            Par exemple: <i> Un crédit approprié doit être accordé à...</i>
          </Fr>
        </SupplementalText>
      </QuestionText>
      <BilingualTextInput
        name="limitations"
        value={record.limitations}
        onChange={handleInputChange}
        multiline
        disabled={disabled}
      />
    </Paper>

    <Paper style={paperClass}>
      <QuestionText>
        <En>Are there any additional comments about this dataset?</En>
        <Fr>
          Y a-t-il des commentaires supplémentaires à propos de cet ensemble de
          données?
        </Fr>
      </QuestionText>
      <BilingualTextInput
        name="comment"
        value={record.comment}
        onChange={handleInputChange}
        multiline
        disabled={disabled}
      />
    </Paper>

    <Paper style={paperClass}>
      <QuestionText>
        <En>Describe the history of this dataset.</En>
        <Fr>Décrivez l'historique de ce jeu de données.</Fr>
      </QuestionText>
      <BilingualTextInput
        name="history"
        value={record.history}
        onChange={handleInputChange}
        multiline
        disabled={disabled}
      />
    </Paper>
  </div>
);

export default MetadataTab;
