import { v4 as uuidv4 } from "uuid";

const blankRecord = {
  title: { en: "", fr: "" },
  abstract: { en: "", fr: "" },
  identifier: uuidv4(),
  keywords: { en: [], fr: [] },
  eov: [],
  progress: "",
  distribution: [],
  dateStart: null,
  dateEnd: null,
  map: { north: "", south: "", east: "", west: "", polygon: "" },
  verticalExtentMin: "",
  verticalExtentMax: "",
  datePublished: null,
  dateRevised: null,
  recordID: "",
  instruments: [],
  platformID: "",
  platformDescription: "",
  language: "",
  license: "",
  contacts: [],
  status: "",
  comment: "",
  limitations: "",
  created: new Date().toISOString(),
  lastEditedBy: {},
  category: "",
  verticalExtentDirection: "",
  datasetIdentifier: "",
  noPlatform: false,
  filename: "",
  organization: "",
  timeFirstPublished: "",
};

export default blankRecord;
