const geographicLocations = [
  // Provinces
  {
    en: "British Columbia",
    fr: "Colombie-Britannique",
    type: "province",
    bbox: { north: 60.0, south: 48.2245, east: -114.0337, west: -139.0536 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Alberta",
    fr: "Alberta",
    type: "province",
    bbox: { north: 60.0, south: 48.9999, east: -110.0053, west: -120.0016 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Saskatchewan",
    fr: "Saskatchewan",
    type: "province",
    bbox: { north: 60.0, south: 48.9999, east: -101.3609, west: -110.0053 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Manitoba",
    fr: "Manitoba",
    type: "province",
    bbox: { north: 60.0, south: 48.9999, east: -95.1562, west: -102.0422 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Ontario",
    fr: "Ontario",
    type: "province",
    bbox: { north: 56.8603, south: 41.6762, east: -74.3418, west: -95.1562 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Quebec",
    fr: "Québec",
    type: "province",
    bbox: { north: 62.5942, south: 44.9904, east: -57.1057, west: -79.7633 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "New Brunswick",
    fr: "Nouveau-Brunswick",
    type: "province",
    bbox: { north: 48.0713, south: 44.5521, east: -63.7697, west: -69.0634 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Nova Scotia",
    fr: "Nouvelle-Écosse",
    type: "province",
    bbox: { north: 47.0323, south: 43.3763, east: -59.6809, west: -66.3282 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Prince Edward Island",
    fr: "Île-du-Prince-Édouard",
    type: "province",
    bbox: { north: 47.0618, south: 45.9488, east: -61.9321, west: -64.4231 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Newfoundland and Labrador",
    fr: "Terre-Neuve-et-Labrador",
    type: "province",
    bbox: { north: 60.3706, south: 46.619, east: -52.6157, west: -67.8017 },
    polygon: null,
    source: "StatCan",
  },
  // Territories
  {
    en: "Yukon",
    fr: "Yukon",
    type: "territory",
    bbox: { north: 69.6454, south: 59.9999, east: -123.8094, west: -141.0017 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Northwest Territories",
    fr: "Territoires du Nord-Ouest",
    type: "territory",
    bbox: { north: 78.7728, south: 59.9997, east: -101.9999, west: -136.4683 },
    polygon: null,
    source: "StatCan",
  },
  {
    en: "Nunavut",
    fr: "Nunavut",
    type: "territory",
    bbox: { north: 83.1116, south: 51.6357, east: -61.1537, west: -120.6611 },
    polygon: null,
    source: "StatCan",
  },
  // Marine Regions
  {
    en: "Gulf of St. Lawrence",
    fr: "Golfe du Saint-Laurent",
    type: "marineRegion",
    bbox: { north: 51.3667, south: 45.5333, east: -52.625, west: -71.1667 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Hudson Bay",
    fr: "Baie d'Hudson",
    type: "marineRegion",
    bbox: { north: 66.0, south: 51.2667, east: -77.0, west: -95.0 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Labrador Sea",
    fr: "Mer du Labrador",
    type: "marineRegion",
    bbox: { north: 67.0, south: 53.0, east: -42.0, west: -64.0 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Strait of Georgia",
    fr: "Détroit de Georgie",
    type: "marineRegion",
    bbox: { north: 50.15, south: 48.2667, east: -122.75, west: -124.9333 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Bay of Fundy",
    fr: "Baie de Fundy",
    type: "marineRegion",
    bbox: { north: 45.8667, south: 44.3, east: -64.3833, west: -66.5167 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Beaufort Sea",
    fr: "Mer de Beaufort",
    type: "marineRegion",
    bbox: { north: 79.0, south: 68.0, east: -120.0, west: -141.0 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Hudson Strait",
    fr: "Détroit d'Hudson",
    type: "marineRegion",
    bbox: { north: 63.7333, south: 59.7667, east: -64.5, west: -79.5 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Davis Strait",
    fr: "Détroit de Davis",
    type: "marineRegion",
    bbox: { north: 70.5, south: 60.0, east: -52.0, west: -70.0 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Baffin Bay",
    fr: "Baie de Baffin",
    type: "marineRegion",
    bbox: { north: 78.6667, south: 70.0, east: -57.0, west: -80.0 },
    polygon: null,
    source: "MarineRegions",
  },
  {
    en: "Gulf of Alaska",
    fr: "Golfe d'Alaska",
    type: "marineRegion",
    bbox: { north: 61.5, south: 53.0, east: -135.0, west: -158.0 },
    polygon: null,
    source: "MarineRegions",
  },
  // Oceans (CF Conventions)
  {
    en: "North Atlantic Ocean",
    fr: "Océan Atlantique Nord",
    type: "ocean",
    bbox: { north: 80.0, south: 0.0, east: 20.0, west: -80.0 },
    polygon: null,
    source: "CF",
  },
  {
    en: "North Pacific Ocean",
    fr: "Océan Pacifique Nord",
    type: "ocean",
    bbox: { north: 65.0, south: 0.0, east: -77.0, west: 99.0 },
    polygon: null,
    source: "CF",
  },
  {
    en: "Arctic Ocean",
    fr: "Océan Arctique",
    type: "ocean",
    bbox: { north: 90.0, south: 65.0, east: 180.0, west: -180.0 },
    polygon: null,
    source: "CF",
  },
];

export default geographicLocations;
