// Port of firebase-functions/functions/translate.js (the `translate` callable).
// Cohere-backed EN<->FR translation with the cioos-commons prompt template
// (glossary baked in by cioos-commons CI).

const fs = require("fs");
const path = require("path");
const { CohereClientV2 } = require("cohere-ai");
const config = require("../config");

const MODEL = "command-a-translate-08-2025";

// Prompt template synced from cioos-commons by generate-translation-config.js.
const promptTemplate = fs.readFileSync(
  path.join(__dirname, "translation-prompt-template.txt"),
  "utf8",
);

// Version metadata (generated by generate-translation-config.js).
let translationMeta = { commonsVersion: "unknown" };
try {
  // eslint-disable-next-line global-require
  translationMeta = require("./translation-meta.json");
} catch {
  // translation-meta.json may not exist in dev; that's ok
}

let client;
function getClient() {
  if (!client) {
    client = new CohereClientV2({
      token: config.cohereApiKey,
      clientName: "cioos-metadata-entry-form",
    });
  }
  return client;
}

function buildPrompt(originalText, sourceLanguageCode, targetLanguageCode) {
  const sourceLang = sourceLanguageCode === "en" ? "Canadian English" : "Canadian French";
  const targetLang = targetLanguageCode === "en" ? "Canadian English" : "Canadian French";

  return promptTemplate
    .replace("{{sourceLang}}", sourceLang)
    .replace("{{targetLang}}", targetLang)
    .replace("{{originalText}}", originalText);
}

function buildTranslationMessage() {
  return `Cohere ${MODEL}, cioos-commons@${translationMeta.commonsVersion}`;
}

// Translate up to 5000 characters at a time using Cohere.
// fromLang is 'en' or 'fr'; the target language is the other one.
async function translateText(text, fromLang) {
  const toLang = fromLang === "en" ? "fr" : "en";
  const prompt = buildPrompt(text, fromLang, toLang);

  const response = await getClient().chat({
    model: MODEL,
    messages: [{ role: "user", content: prompt }],
  });

  if (response.message && response.message.content && response.message.content.length > 0) {
    let translatedText = response.message.content[0].text;
    // Strip <text_to_translate> wrapper tags if the model echoes them back
    const match = translatedText.match(
      /<text_to_translate>\s*([\s\S]*?)\s*<\/text_to_translate>/,
    );
    if (match) translatedText = match[1];
    return {
      translatedText,
      translationMessage: buildTranslationMessage(),
    };
  }
  throw new Error("No translation received from Cohere API");
}

module.exports = { translateText, buildPrompt, buildTranslationMessage, MODEL };
