-- Up Migration

-- Idempotency key for records created offline.
--
-- Without this, a create retried after a lost response silently produces a
-- duplicate record: POST /records is a bare INSERT with no ON CONFLICT, and
-- records.identifier — the obvious candidate — is only a plain index, is
-- semantically the *dataset* identifier that leaks into filenames and DOIs,
-- and is regenerated by clone. A request key and a dataset identity are
-- different concepts with different lifetimes.
--
-- Scoped to (region, user_id) so one user's client cannot squat another's key,
-- and partial so the web SPA — which never sends one — is entirely unaffected.
-- Same shape as the existing records_firebase_key_idx.
ALTER TABLE records ADD COLUMN client_record_id text;

CREATE UNIQUE INDEX records_client_record_id_idx
  ON records (region, user_id, client_record_id)
  WHERE client_record_id IS NOT NULL;

-- Down Migration

DROP INDEX records_client_record_id_idx;
ALTER TABLE records DROP COLUMN client_record_id;
