export const keywordListFr = [
  "abondance et biomasse",
  "accès à la mer",
  "aide à la décision",
  "aires protégées",
  "ressources maritime",
  "amélioration des connaissances",
  "aménagement du territoire",
  "assainissement des eaux",
  "bar rayé",
  "bassin versant",
  "caractérisation des habitats",
  "caractérisation des rives",
  "changement climatique",
  "chlorophylle a",
  "conservation des ressources",
  "consommation d'eau",
  "courant marin",
  "crustacé",
  "débits eau douce",
  "densité eau",
  "développement durable",
  "échange océan-atmosphère",
  "échantillonnage",
  "écrevisses",
  "entreprises de maricultures",
  "érosion des côtes",
  "espèces en péril",
  "espèces envahissante",
  "flore côtière",
  "fluorescence",
  "fraie",
  "gestion communautaire",
  "gestion des ressources",
  "gestion intégrée",
  "glace de mer",
  "habitat sensible",
  "habitats important",
  "hydrocarbure",
  "incidents",
  "informations générales",
  "inventaire faunique",
  "inventaire poisson",
  "macroalgue",
  "macrofaune benthique",
  "mammifères marins",
  "marais",
  "météorologie",
  "milieux humides",
  "milieux naturels d'intérêt",
  "mise en valeur",
  "missions océanographique",
  "mollusque",
  "niveau eau",
  "oiseaux marins",
  "oiseaux migrateurs",
  "pêches commerciales",
  "pêches expérimentales",
  "physico-chimie",
  "phytoplancton",
  "plantes aquatique",
  "poisson",
  "pollution côtière",
  "pression atmosphérique",
  "protection des côtes",
  "protection des habitats",
  "qualité eau",
  "radiation",
  "ressources maritimes",
  "réhabilitation écologique",
  "restauration des rives",
  "restauration expérimentale",
  "restauration habitat",
  "risques côtiers",
  "saisie citoyenne",
  "salinité",
  "sédiment",
  "sites de pêches",
  "suivi annuel",
  "suivi des espèces",
  "suivi habitat",
  "taxonomie",
  "télédétection",
  "température de l'eau",
  "tortue de mer",
  "utilisation du territoire",
  "utilisation durable",
  "vagues",
  "vents",
  "zone côtière",
];

export const keywordListEn = [
  "abundance and biomass",
  "sea access",
  "decision making",
  "protected areas",
  "maritime ressources",
  "knowledge improvement",
  "land-use planning",
  "water purification",
  "striped bass",
  "watershed",
  "habitat characterization",
  "coastal characterization",
  "climate change",
  "chlorophyll a",
  "resource conservation",
  "water consumption",
  "sea currents",
  "crustacean",
  "fresh water flow",
  "water density",
  "sustainable development",
  "ocean-atmosphere exchange",
  "sampling",
  "crayfish",
  "mariculture",
  "coastal erosion",
  "endangered species",
  "invasive species",
  "coastal flora",
  "fluorescence",
  "spawning",
  "community management",
  "resource management",
  "integrated management",
  "sea ice",
  "sensitive habitat",
  "important habitat",
  "hydrocarbon",
  "incidents",
  "general information",
  "wildlife inventory",
  "fish inventory",
  "macroalgae",
  "benthic macrofauna",
  "marine mammal",
  "marsh",
  "meteorology",
  "wetlands",
  "natural environments of interest",
  "enhancement",
  "oceanographic missions",
  "mollusc",
  "sea level",
  "seabirds",
  "migrator birds",
  "commercial fisheries",
  "experimental fisheries",
  "physical-chemical",
  "phytoplankton",
  "sea grass",
  "fish",
  "coastal pollution",
  "atmospheric pressure",
  "coast protection",
  "habitat protection",
  "water quality",
  "radiation",
  "maritime resources",
  "ecological rehabilitation",
  "shore restoration",
  "experimental restoration",
  "habitat restoration",
  "coastal risks",
  "citizen data",
  "salinity",
  "sediment",
  "fishing sites",
  "annual follow-up",
  "species tracking",
  "habitat tracking",
  "taxonomy",
  "remote sensing",
  "water temperature",
  "sea turtles",
  "land-use",
  "sustainabilty",
  "waves",
  "wind",
  "coastal zone",
];

export const keywordLists = { fr: keywordListFr, en: keywordListEn };
