export const keywordList = [
  "abondance et biomasse",
  "accès à la mer",
  "aide à la décision",
  "aires protégées",
  "ressources maritime",
  "amélioration des connaissances",
  "aménagement du territoire",
  "assainissement des eaux",
  "bar rayé",
  "bassin versant",
  "caractérisation des habitats",
  "caractérisation des rives",
  "changement climatique",
  "chlorophylle a",
  "conservation des ressources",
  "consommation d'eau",
  "courant marin",
  "crustacé",
  "débits eau douce",
  "densité eau",
  "développement durable",
  "échange océan-atmosphère",
  "échantillonnage",
  "écrevisses",
  "entreprises de maricultures",
  "érosion des côtes",
  "espèces en péril",
  "espèces envahissante",
  "flore côtière",
  "fluorescence",
  "fraie",
  "gestion communautaire",
  "gestion des ressources",
  "gestion intégrée",
  "glace de mer",
  "habitat sensible",
  "habitats important",
  "hydrocarbure",
  "incidents",
  "informations générales",
  "Inventaire faunique",
  "inventaire poisson",
  "macroalgue",
  "macrofaune benthique",
  "mammifères marins",
  "marais",
  "marais salée",
  "marées",
  "météorologie",
  "milieux humides",
  "milieux naturels d'intérêt",
  "mise en valeur",
  "missions océanographique",
  "mollusque",
  "niveau eau",
  "oiseaux marins",
  "oiseaux migrateurs",
  "pêches commerciales",
  "pêches expérimentales",
  "physico-chimie",
  "phytoplancton",
  "plantes aquatique",
  "poisson",
  "pollution côtière",
  "pression atmosphérique",
  "protection des côtes",
  "protection des habitats",
  "qualité eau",
  "radiation",
  "ressources maritimes",
  "réhabilitation écologique",
  "restauration de plage",
  "restauration des rives",
  "restauration expérimentale",
  "restauration habitat",
  "risques côtiers",
  "saisie citoyenne",
  "salinité",
  "sédiment",
  "sites de pêches",
  "suivi annuel",
  "suivi des espèces",
  "suivi habitat",
  "taxonomie",
  "télédétection",
  "température de l'eau",
  "tortue de mer",
  "utilisation du territoire",
  "utilisation durable",
  "vagues",
  "vents",
  "zone côtière",
];