const keywordList = [
  "abundance and biomass",
  "sea access",
  "decision making",
  "protected areas",
  "maritime ressources",
  "knowledge improvement",
  "land-use planning",
  "water purification",
  "striped bass",
  "watershed",
  "habitat characterization",
  "coastal characterization",
  "climate change",
  "chlorophyll a",
  "resource conservation",
  "water consumption",
  "sea currents",
  "crustacean",
  "fresh water flow",
  "water density",
  "sustainable development",
  "ocean-atmosphere exchange",
  "sampling",
  "crayfish",
  "mariculture",
  "coastal erosion",
  "endangered species",
  "invasive species",
  "coastal flora",
  "fluorescence",
  "spawning",
  "community management",
  "resource management",
  "integrated management",
  "sea ice",
  "sensitive habitat",
  "important habitat",
  "hydrocarbon",
  "incidents",
  "general information",
  "wildlife inventory",
  "fish inventory",
  "macroalgae",
  "benthic macrofauna",
  "marine mammal",
  "marsh",
  "meteorology",
  "wetlands",
  "natural environments of interest",
  "enhancement",
  "oceanographic missions",
  "mollusc",
  "sea level",
  "seabirds",
  "migrator birds",
  "commercial fisheries",
  "experimental fisheries",
  "physical-chemical",
  "phytoplankton",
  "sea grass",
  "fish",
  "coastal pollution",
  "atmospheric pressure",
  "coast protection",
  "habitat protection",
  "water quality",
  "radiation",
  "maritime resources",
  "ecological rehabilitation",
  "shore restoration",
  "experimental restoration",
  "habitat restoration",
  "coastal risks",
  "citizen data",
  "salinity",
  "sediment",
  "fishing sites",
  "annual follow-up",
  "species tracking",
  "habitat tracking",
  "taxonomy",
  "remote sensing",
  "water temperature",
  "sea turtles",
  "land-use",
  "sustainabilty",
  "waves",
  "wind",
  "coastal zone",
];

export default keywordList
