name: Deploy to Firebase Hosting on PR and Dev Push
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  build_and_preview:
    # UPDATED: Allow the job to run on pushes OR PRs from the main repo
    if: |
      github.event_name == 'push' || 
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)

    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Set up Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - name: Install and Build 🔧
        env:
          VITE_DEV_DEPLOYMENT: true
          VITE_BASE_PATH: /
          VITE_GOOGLE_CLOUD_API_KEY: ${{ secrets.REACT_APP_GOOGLE_CLOUD_API_KEY }}
          VITE_GOOGLE_CLOUD_API_KEY_DEV: ${{ secrets.REACT_APP_GOOGLE_CLOUD_API_KEY_DEV }}
        run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CIOOS_METADATA_FORM }}'
          expires: 30d
          entryPoint: '.'
          projectId: cioos-metadata-form-dev-258dc
          channelId: ${{ github.ref_name == 'development' && 'development' || '' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESSKEYID: ${{ secrets.AWS_ACCESSKEYID }}
          AWS_SECRETACCESSKEY: ${{ secrets.AWS_SECRETACCESSKEY }}
          GITHUB_AUTH: ${{ secrets.ISSUE_CREATOR_PAT }}
          VITE_GOOGLE_CLOUD_API_KEY: ${{ secrets.REACT_APP_GOOGLE_CLOUD_API_KEY }}
          VITE_GOOGLE_CLOUD_API_KEY_DEV: ${{ secrets.REACT_APP_GOOGLE_CLOUD_API_KEY_DEV }}
          PROJECT_PATH: ./firebase-functions
          VITE_DEV_DEPLOYMENT: true